# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - AzureFunctionsTradingApp and angular app to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: 

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'AzureFunctions'
  DOTNET_VERSION: '8.0.x'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      UI_CHANGED: ${{ steps.set_outputs.outputs.UI_CHANGED }}
      WORKFLOWS_CHANGED: ${{ steps.set_outputs.outputs.WORKFLOWS_CHANGED }}
      BE_CHANGED: ${{ steps.set_outputs.outputs.BE_CHANGED }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get list of modified files
        run: |
          git fetch --prune --unshallow
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed-files.txt
          echo "Changed files:"
          cat changed-files.txt

      - name: Check if tradingwebapp.client or workflows changed
        id: set_outputs
        run: |
          UI_CHANGED=false
          WORKFLOWS_CHANGED=false
          BE_CHANGED=false

          if grep -q "^TradingWebApp.UI/" changed-files.txt; then
            echo "UI project has changed"
            UI_CHANGED=true
          fi

          if grep -q "^.github/workflows" changed-files.txt; then
            echo "Workflows have changed"
            WORKFLOWS_CHANGED=true
          fi

          if grep -qv "^.github/workflows" changed-files.txt && grep -qv "^TradingWebApp.UI" changed-files.txt; then
            echo "Backend project has changed"
            BE_CHANGED=true
          fi

          echo "::set-output name=UI_CHANGED::${UI_CHANGED}"
          echo "::set-output name=WORKFLOWS_CHANGED::${WORKFLOWS_CHANGED}"
          echo "::set-output name=BE_CHANGED::${BE_CHANGED}"

  build-and-deploy-azure-functions:
    runs-on: ubuntu-latest
    needs: check-changes
    if: ${{ needs.check-changes.outputs.WORKFLOWS_CHANGED == 'true' || needs.check-changes.outputs.BE_CHANGED == 'true' }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3B287AC6E4DD4127B3760A5B325B589B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9F959F769B14D058B98100F7D46D37F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_75C65CD261524417A3FCEC5B68C2496D }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'AzureFunctionsTradingApp'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

  build-and-deploy-angular-ui:
    runs-on: ubuntu-latest
    needs: check-changes
    if: ${{ needs.check-changes.outputs.WORKFLOWS_CHANGED == 'true' || needs.check-changes.outputs.UI_CHANGED == 'true' }}
    permissions:
      contents: write
      pages: write
    defaults:
      run:
        working-directory: ./TradingWebApp.UI

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          npm run build -- --output-path=${{ github.workspace }}/angular_output --base-href=/$REPO_NAME/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/angular_output # because of the working-directory set
          